# Generated by Django 5.1 on 2024-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msgboard',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('profilePic', models.TextField()),
                ('permissionLevel', models.CharField(choices=[('admin', 'Admin'), ('normal_user', 'Normal User'), ('viewer', 'Viewer')], max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('password', models.TextField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
            ],
        ),
    ]
